name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python env
        uses: actions/setup-python@v2

      - name: Setup pre-commit
        uses: pre-commit/action@v2.0.3

  lint:
    name: Typescript Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@master

      - name: Install Node modules
        run: |
          yarn install

      - name: Lint source files
        run: |
          yarn tsc

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@master

      - name: Install Node modules
        run: |
          yarn install

      - name: Run tests
        run: |
          yarn test
