name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@master

      - name: Install Node modules
        run: |
          yarn install

      - name: Run test
        run: |
          yarn test
